# Generated by Django 4.0.3 on 2022-03-06 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novatech', '0002_alter_records_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='records',
            old_name='id',
            new_name='record_id',
        ),
    ]
